apiVersion: v1
kind: PersistentVolume
metadata:
  name: projet-apache-pv
  labels:
    storage-tier: wordpress
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/gitlab-runner/www/projet/"
