apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: projet
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb-claim0
  name: mariadb-claim0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      storage-tier: mysql
status: {}
