apiVersion: v1
kind: PersistentVolume
metadata:
  name: projet-mariadb-pv
  labels:
    storage-tier: mysql
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/gitlab-runner/mysql/projet"
